### ISSUE TITLE
Using a custom theme is broken

### ISSUE THREAD

**Issue by nburwell** [patternpack/patternpack#46]
STR:
1. Created "my-patternpack-theme" folder with same structure as the patternpack-example-theme in the root of my project
2. Used the following config with theme:

```
grunt.initConfig({
    patternpack: {
      options: {
        assets: "./src/assets",
        theme: "./my-patternpack-theme"
      },

      run: {},
      build: {},
      release: {}
    }
  });
```
1. Get the following error when running grunt:

```
> grunt
Running "patternpack:run" (patternpack) task
Warning: path is not defined Use --force to continue.

Aborted due to warnings.
```

**Expected results:**
Locate and use "my-patternpack-theme" correctly, and launch server, when running `grunt`

**Comment by johngully** [comment]
I actually ran across the same problem last night.  Thank you so much for your contribution to the project.

Please feel to join our project Slack 
https://patternpack.slack.com

**Comment by johngully** [comment]
Please feel to join our project Slack 
https://patternpack.slack.com

**Comment by marcelosomers** [comment]
@nburwell Thanks for the contribution!

If you're interested in joining our Slack channel above, let me know your email and I'll get you an invite.

**Comment by nburwell** [comment]
Would love to join the slack group. Can you send an invite to nburwell AT gmail DOT com please?
