### ISSUE TITLE
Handling Quick CSS Testing/Development

### ISSUE THREAD

**Issue by marcelosomers** [patternpack/patternpack#6]
Currently, if PatternPack lives in it's own repo and is serving up the styles to an app via npm/bower, there's a big developer roadblock. Testing out quick changes in my CSS requires:
1. Make changes in the library's Sass
2. Build those changes
3. Cut a release
4. Run `npm update` in the parent project

If used properly, this should be ok because you are updating patterns in the library, and simply importing them back to the app.

However, situations may arise where you quickly need to test out CSS from the library in your main project. This becomes very tedious to cut several releases.

Here's a proposed fix that I've tested locally but haven't generalized.
1. PatternPack would include a task that copies CSS to a configurable location (e.g., `patternPack:remoteCopy`)
2. In your main project, you could configure a remoteCopy task that accepts a location
3. Best practice would be to define that copy location in a separate file, like many deployment grunt tasks do (e.g., [grunt-sftp-deploy](https://github.com/thrashr888/grunt-sftp-deploy) just accepts a key name that gets defined in a `.ftpass` JSON file)

Thoughts?

**Comment by johngully** [comment]
An initial pass at this functionality has been addressed in https://github.com/patternpack/patternpack/pull/7
