### ISSUE TITLE
Question: Any idea if there will be a gulp version of this?

### ISSUE THREAD

**Issue by changalberto** [patternpack/patternpack#69]

**Comment by marcelosomers** [comment]
Alberto - as of today, it's not possible. PatternPack uses [Assemble](http://assemble.io) as its static site generator, which only supports grunt. The Assemble team claims they are working on a gulp version, which we'd look into supporting. 

Hopefully the choice of Grunt won't limit you though. The idea behind PatternPack is that you are extracting your UI code from your main app. So while you may use Gulp today for your app(s), your PatternPack can still use Grunt without interfering. 

Thanks so much for your comment! Please let us know how else we can help you with PatternPack. I'm closing this for now.
