### ISSUE TITLE
Generating section index files?

### ISSUE THREAD

**Issue by ashooner** [patternpack/patternpack#78]
Is there a recommended method for concatenating the individual `.md` files within a `patternStructure` directory into the `index.html`for that directory?

**Comment by johngully** [comment]
Yes!  The [PatternPack Example Library](https://github.com/patternpack/patternpack-example-library) does have an example of this.  Review the `src/atoms/index.hbs` to [see how its done](https://github.com/patternpack/patternpack-example-library/blob/master/src/atoms/index.hbs).

Behind the scenes PatternPack uses [Assemble](http://www.assemble.io) to generate all the static assets.  So if you want to dig into all the possible options for templating you will want to review there docs (which unfortunately are not the best right now).

**Comment by johngully** [comment]
We are really glad to have you using PatternPack!  We like to keep GitHub issues for problems with the software.  For "how to" discussions we prefer to use the slack channel https://patternpack.slack.com  Please join us there and we would love to help you get an awesome pattern library up and running :smile:

**Comment by ashooner** [comment]
Awesome, thanks! Sorry, somehow missed the slack channel.
