### ISSUE TITLE
Remove dependency on ruby

### ISSUE THREAD

**Issue by noelklein** [patternpack/patternpack#83]
Is it possible to remove the dependency on ruby by switching to node-sass?

https://www.npmjs.com/package/node-sass

It would also be great to remove the dependency on a globally installed grunt by specifying npm scripts that use the grunt in ./node_modules/.bin/grunt instead.

Ideally the project would just require node and to run it all we need is `git clone ... && npm install && npm start`. What do you guys think?

**Comment by marcelosomers** [comment]
Where are we dependent on ruby sass? [Grunt-sass uses node-sass](https://github.com/sindresorhus/grunt-sass).

**Comment by marcelosomers** [comment]
Also, on the global grunt comment - is this in reference to running/testing the patternpack codebase itself, or to include it in another project (e.g., I'm using PatternPack to build a pattern library)?

**Comment by noelklein** [comment]
I pulled a project that uses pattern pack and that required ruby for sass and scss linting. Sorry for the confusion!
That same project also requires grunt to be installed globally. I guess I'll have to contact the maintainer of that other project...
